### ISSUE TITLE
publish new shuffle procedure to Akku

### ISSUE THREAD

**Issue by maniacalwhistle** [hinkelman/chez-stats#10]
Hi!

Thanks for your work on this package. I was working on something and found myself implementing a custom procedure that turns out to be similar to `(shuffle)`, which I see was added about 4 months ago. But I don't seem to be able to call that procedure (even though I can call the rest of them).

I installed `chez-stats` about a week ago using Akku (`akku install chez-stats` and `akku install chez-stats@^0.1.2`). But `(shuffle)` isn't showing up. I wonder if I am just not getting the most recent contents/source code based on how I am installing the package, etc.?  Is it possible that the most recent change needs to be published/pushed to Akku?

When I look at `~/.akku/src/chez-stats/chez-stats.sls` or `/.akku/src/chez-stats/chez-stats/random.sls` I don't see `shuffle` in the code like I do on Github.

A call to `akku show chez-stats` returns:
```
;;; note: source file /usr/local/Cellar/akku/1.1.0/share/akku/guile/site/3.0/spells/string-utils.scm
;;;       newer than compiled /usr/local/Cellar/akku/1.1.0/lib/akku/guile/3.0/site-ccache/spells/string-utils.go
;;; note: source file /usr/local/Cellar/akku/1.1.0/share/akku/guile/site/3.0/akku/config.scm
;;;       newer than compiled /usr/local/Cellar/akku/1.1.0/lib/akku/guile/3.0/site-ccache/akku/config.go
WARNING: (guile-user): imported module (rnrs) overrides core binding `newline'
WARNING: (guile-user): imported module (rnrs) overrides core binding `display'
WARNING: (guile-user): imported module (rnrs) overrides core binding `error'
WARNING: (guile-user): imported module (rnrs) overrides core binding `read'
WARNING: (guile-user): imported module (rnrs) overrides core binding `map'
chez-stats 0.1.2 - Read and write delimited text files, compute descriptive statistics, and generate random variates in Chez Scheme.

Metadata
Author:        Travis Hinkelman

Dependencies
chez-srfi      >=0.0.0-akku <1.0.0      (>=0.0.0-akku <1.0.0)

Source code
URL:           https://archive.akkuscm.org/archive/pkg/c/chez-stats_0.1.2_repack.tar.xz
Content:       (sha256 "11d568d7424dd90f0c5e72c8127eb0134c2b50d2ac8f3fb50938d0a392613e89")

Available versions
0.1.0
0.1.1
0.1.2
```

Let me know if I can provide more information to help debug.

Thanks,
Michael

**Comment by hinkelman** [comment]
Hi Michael,

You are correct that I hadn't published the addition of the `shuffle` procedure to Akku. I've just submitted that change to Akku. Hopefully, it will be updated in the next couple of days.

Thanks,

Travis
