### ISSUE TITLE
Add sum procedure

### ISSUE THREAD

**Issue by thinkelman-ESA** [hinkelman/chez-stats#11]
I didn't initially include `(sum lst)` because it only saved a few characters over `(apply + lst)`, but it would also be useful to sum across a boolean list, which you can't do with `(apply + lst)`, and that tips the scales in favor of including it.

**Comment by hinkelman** [comment]
Added in [d06a6e5](https://github.com/hinkelman/chez-stats/commit/d06a6e53612957ef2319812befc4e696745dee51)
