### ISSUE TITLE
add gh-pages

### ISSUE THREAD

**Issue by guenchi** [hinkelman/chez-stats#2]
please add gh-pages brach so I can pull request from 

https://github.com/guenchi/chez-stats/tree/gh-pages

which give chez-stats library a official page like: https://guenchi.github.io/chez-stats/

in https://hinkelman.github.io/chez-stats/

**Comment by hinkelman** [comment]
Done. Thanks for your guidance.

**Comment by hinkelman** [comment]
Sorry. I just realized that you simply wanted me to create the branch so that you could create a pull request. Instead, I recreated your files in my repo. Hopefully, that also works for you. Thanks.

**Comment by guenchi** [comment]
even better
